[tool.poetry]
name = "olcf_api"
version = "0.1.0"
description = ""
authors = ["David M. Rogers <predictivestatmech@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.101.1"
uvicorn = "^0.23.2"
aiohttp = "^3.8.5"
python-multipart = "^0.0.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
